apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: ca2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: 913210542757.dkr.ecr.us-east-2.amazonaws.com/ca2-producer:v2
          envFrom:
            - configMapRef:
                name: producer-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
