apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: ca2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: processor-reader
  namespace: ca2
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processor-reader-binding
  namespace: ca2
subjects:
  - kind: ServiceAccount
    name: processor-sa
    namespace: ca2
roleRef:
  kind: Role
  name: processor-reader
  apiGroup: rbac.authorization.k8s.io
