apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-config
  namespace: ca2
data:
  KAFKA_BROKER: "kafka:9092"
  KAFKA_TOPIC: "auth-events"
  MONGODB_DATABASE: "threat_monitor"
  MONGODB_COLLECTION: "security_events"
  API_PORT: "8080"
