apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: ca2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      serviceAccountName: processor-sa

      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z kafka 9092; do
                echo "Waiting for Kafka..."
                sleep 3
              done
              echo "Kafka is ready."

      containers:
        - name: processor
          image: 913210542757.dkr.ecr.us-east-2.amazonaws.com/ca2-processor:v1
          envFrom:
            - configMapRef:
                name: processor-config
            - secretRef:
                name: processor-secret
          ports:
            - containerPort: 8080
              name: http
